version: '3.8'

services:
  backend:
    build: .
    container_name: timetable-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=securepassword
      - DB_NAME=timetable
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: timetable-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=timetable
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: timetable-redis
    ports:
      - "6379:6379"

volumes:
  db_data: